using System;using System.IO;using System.Drawing;using System.Threading;using System.Windows.Forms;using System.Collections.Generic;
class ManagerLocaleSyncTests {
 static readonly object gate=new object();static readonly ManualResetEvent releaseArabic=new ManualResetEvent(false);static int arabicCalls,englishCalls;static string hostLocale="en";static int revision=1;static bool unknown;
 static Dictionary<string,object> D(params object[] values){var d=new Dictionary<string,object>();for(int i=0;i<values.Length;i+=2)d.Add((string)values[i],values[i+1]);return d;}
 static Dictionary<string,object> Ui(){return D("hostInstanceId","test-host","capabilities",new object[]{"ui-locale-v1"},"requestedLocale",hostLocale,"appliedLocale",hostLocale,"acceptedRevision",revision,"appliedRevision",revision,"pendingReason",null,"components",D("controller","applied","runtime","absent"));}
 static Dictionary<string,object> Run(string action,string value){if(action=="stop")return D("restoration","unknown");if(action=="ui-language"){if(value=="ar"){Interlocked.Increment(ref arabicCalls);if(!releaseArabic.WaitOne(6000))throw new Exception("Test Arabic gate timed out");}else Interlocked.Increment(ref englishCalls);lock(gate){hostLocale=value;revision++;return D("ui",Ui(),"deferred",false);}}lock(gate)return D("host",true,"hostInstanceId","test-host","ui",Ui(),"operation",D("result",unknown?"unknown":"succeeded"),"resources",true,"restoration","unknown","preference",D("theme","astra-night","environmentDensity","balanced"));}
 class Quiet:ManagerForm {internal Quiet(UiContext ui):base(Run,ui){StartPosition=FormStartPosition.Manual;Location=new Point(-10000,-10000);}protected override bool ShowWithoutActivation{get{return true;}}}
 static Control Find(Control form,string name){return form.Controls.Find(name,true)[0];}
 static void Until(Func<bool> ready,string failure,int timeout=8000){var watch=System.Diagnostics.Stopwatch.StartNew();while(!ready()&&watch.ElapsedMilliseconds<timeout){Application.DoEvents();Thread.Sleep(5);}if(!ready())throw new Exception(failure);}
 [STAThread] static int Main(string[] args){try{Entry.Root=args[0];Entry.Data=Path.Combine(args[1],"state");Directory.CreateDirectory(Entry.Data);UiSettings.Save(Entry.Data,"en");Application.EnableVisualStyles();var ui=UiContext.Create("en","en",Path.Combine(Entry.Root,"localization"));Entry.Ui=ui;var form=new Quiet(ui);form.Show();Until(()=>Find(form,"languageStatus").Text==ui.Catalogue.Text("status.localeSynced"),"Initial matching host language did not confirm");
  ((ComboBox)Find(form,"languageChoice")).SelectedIndex=5;Until(()=>Volatile.Read(ref arabicCalls)==1,"Saved Arabic choice did not request synchronization");((ComboBox)Find(form,"languageChoice")).SelectedIndex=2;releaseArabic.Set();Until(()=>Volatile.Read(ref englishCalls)==1&&Find(form,"languageStatus").Text==ui.Catalogue.Text("status.localeSynced"),"Older Arabic response replaced latest English choice");
  if(Entry.Ui.Locale!="en"||UiSettings.Read(Entry.Data).Language!="en")throw new Exception("Latest persistent choice changed");
  lock(gate)unknown=true;Find(form,"refresh").PerformClickCompat();Until(()=>Find(form,"diagnosticDetail").Text.Length>0,"Status did not refresh");((ComboBox)Find(form,"languageChoice")).SelectedIndex=5;var wait=System.Diagnostics.Stopwatch.StartNew();while(wait.ElapsedMilliseconds<500){Application.DoEvents();Thread.Sleep(5);}if(arabicCalls!=1)throw new Exception("Unknown operation allowed another locale request");
  releaseArabic.Set();form.Close();Until(()=>form.IsDisposed,"Close did not drain");Console.WriteLine("Latest choice / old ACK / unknown operation PASS");return 0;
 }catch(Exception e){Console.Error.WriteLine(e);return 1;}finally{releaseArabic.Set();}}
}
static class ButtonTestExtension {internal static void PerformClickCompat(this Control control){((Button)control).PerformClick();}}
