import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {deflateSync,deflateRawSync} from 'node:zlib';
const home=await mkdtemp(join(tmpdir(),'silver-pack-test-'));process.env.LOCALAPPDATA=home;
const p=await import('../src/runtime/packs.mjs');
const table=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
const crc=b=>{let n=0xffffffff;for(const x of b)n=table[(n^x)&255]^(n>>>8);return(n^0xffffffff)>>>0;};
function chunk(name,data){const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(name,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;}
function png(){const h=Buffer.alloc(13);h.writeUInt32BE(64);h.writeUInt32BE(64,4);h[8]=8;h[9]=6;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',h),chunk('IDAT',deflateSync(Buffer.alloc(64*257))),chunk('IEND',Buffer.alloc(0))]);}
async function zip(name,entries){let offset=0,locals=[],central=[];for(const [n,value] of entries){const data=Buffer.isBuffer(value)?value:Buffer.from(value),file=Buffer.from(n),packed=deflateRawSync(data),sum=crc(data),head=Buffer.alloc(30),dir=Buffer.alloc(46);head.writeUInt32LE(0x04034b50);head.writeUInt16LE(20,4);head.writeUInt16LE(8,8);head.writeUInt32LE(sum,14);head.writeUInt32LE(packed.length,18);head.writeUInt32LE(data.length,22);head.writeUInt16LE(file.length,26);dir.writeUInt32LE(0x02014b50);dir.writeUInt16LE(20,4);dir.writeUInt16LE(20,6);dir.writeUInt16LE(8,10);dir.writeUInt32LE(sum,16);dir.writeUInt32LE(packed.length,20);dir.writeUInt32LE(data.length,24);dir.writeUInt16LE(file.length,28);dir.writeUInt32LE(offset,42);locals.push(head,file,packed);central.push(dir,file);offset+=head.length+file.length+packed.length;}
 const cd=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(cd.length,12);end.writeUInt32LE(offset,16);const file=join(home,name+'.zip');await writeFile(file,Buffer.concat([...locals,cd,end]));return file;}
function manifest(version='1.0.0'){return {schemaVersion:1,kind:'character',id:'local.astra.original',version,name:'Safe',creator:'Tests',compatibility:{packApi:1,requiredCapabilities:['character.static.v1'],styleFamily:'silver-scale',pages:['home','conversation'],appearances:['light','dark']},preview:'previews/cover.png',credits:'CREDITS.md',rights:{distribution:'local-only',licenseFile:'ASSET_LICENSE.md',evidenceFile:'PROVENANCE.md'},layout:{canvas:{width:64,height:64},anchor:{x:.5,y:.9},contentBounds:{x:0,y:0,width:1,height:1}},states:{idle:{poster:'states/idle.png'}},fallbacks:{error:'idle',long_wait:'idle'}};}
function entries(m){return [['manifest.json',JSON.stringify(m)],['states/idle.png',png()],['previews/cover.png',png()],['CREDITS.md','test'],['ASSET_LICENSE.md','test only'],['PROVENANCE.md','synthetic']];}
test('import/select separated; failure never overwrites; remove protects selected; versions retained',async()=>{
 const first=await p.importDataPack(await zip('one',[['states/',''],['previews/',''],...entries(manifest())]));assert.equal(first.key,'local.astra.original@1.0.0');assert.equal((await p.listPacks()).selection.character,'__legacy__');await p.setSelection('character',first.key);
 const before=await p.listPacks();for(const [name,mutate] of [['traversal',e=>e.push(['../escape.png',png()])],['casecollision',e=>e.push(['STATES/IDLE.png',png()])],['executable',e=>e.push(['evil.js','x'])],['broken',e=>e[1][1]=Buffer.from('broken')],['sameversion',e=>e[3][1]='modified']]){const e=entries(manifest());mutate(e);await assert.rejects(p.importDataPack(await zip(name,e)));assert.deepEqual(await p.listPacks(),before);}
 const badUpdate=entries(manifest('1.0.1'));badUpdate[1][1]=Buffer.from('broken');await assert.rejects(p.importDataPack(await zip('bad-update',badUpdate)));assert.deepEqual(await p.listPacks(),before);
 await p.importDataPack(await zip('good-update',entries(manifest('1.0.1'))));assert.equal((await p.listPacks()).packs.length,2);assert.equal((await p.listPacks()).selection.character,first.key);const resource=await p.loadPack('character',first.key);assert.equal(resource.assets.idle,resource.assets.error);await assert.rejects(p.removePack(first.key));await p.setSelection('character','__legacy__');await p.removePack(first.key);assert.equal((await p.listPacks()).packs.length,1);
 const archived=manifest();archived.id='local.astra.q';const q=await p.importDataPack(await zip('archived-q',entries(archived)));const all=await p.listPacks();assert.ok(all.packs.some(row=>row.key===q.key));await assert.rejects(p.loadPack('character',q.key),/封存/);await assert.rejects(p.setSelection('character',q.key),/封存/);assert.deepEqual(await p.listPacks(),all);assert.ok(!(await p.enabledPacks()).enabledPacks.some(row=>row.key===q.key));
});
